### ISSUE TITLE
Missing HEADER_UDX in OrderInfo

### ISSUE THREAD

**Issue by Flow09AT** [Naugrimm/opentrans#12]
Currently we would need HEADER_UDX to be implemented in OrderInfo

![image](https://github.com/Naugrimm/opentrans/assets/72448580/aaf30496-68a2-457c-a0d3-a23da82b98d2)
![image](https://github.com/Naugrimm/opentrans/assets/72448580/7bd8fab8-05e8-4fbc-b4f6-4b95692657e9)

**Comment by Naugrimm** [comment]
fixed by #13
